x = ("samsung", "iphone", "tecno", "redmi")
print(x[0])
print(x[-2])
temp = list(x)
temp[1] = "itel"
x = tuple(temp)
print(x)
temp = list(x)
temp.append("Huawei")
x = tuple(temp)
print(x)
for phone in x:
    print(phone)
temp = list(x)
temp.pop(0)
x = tuple(temp)
print(x)
cities = tuple(("Kampala", "Entebbe", "Gulu", "Mbarara"))
print(cities)
(a, b, c, d) = cities
print(a, b, c, d)
print(cities[1:4])
first_names = ("Alice", "Bob")
second_names = ("Smith", "Johnson")
full_names = first_names + second_names
print(full_names)
colors = ("red", "blue")
print(colors * 3)
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)
print(thistuple.count(8))
